title: Gravidade Zero
remote_theme: jekyll/minima@master
author:
  name: Carol the Astronaut
instagram_username: caroltheastronaut
url: https://www.caroltheastronaut.com
plugins:
  - jekyll-feed
  - jekyll-remote-theme
