title: Gravidade Zero
remote_theme: jekyll/minima@master
author:
  name: Carol the Astronaut
minima:
  social_links:
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/caroltheastronaut"
    - title: Website
      icon: link
      url: "https://www.caroltheastronaut.com"
url: https://caroltheastronaut.github.io/gravidadezero
plugins:
  - jekyll-feed
  - jekyll-remote-theme
